name: Website Test

on:
  #  schedule:
  #    - cron:  '0 12 * * 1-4' # every day 12:00 UTC Monday-Thursday

  # manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest # The first job utilizes windows-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the release
        run: yarn build

      - name: Upload Artifacts 🔺 # The project is then uploaded as an artifact named 'site'.
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: build

  deploy:
    if: github.event_name != 'pull_request'
    needs: [build] # The second job must depend on the first one to complete before running, and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Download Artifacts 🔻 # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v1
        with:
          name: site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          repository-name: FeSwap/TestSite
          token: ${{ secrets.GH_DEPLOY_TOKEN }}
          folder: 'site' # The deployment folder should match the name of the artifact. Even though our project builds into the 'build' folder the artifact name of 'site' must be placed here.



#  gh-release:
#    if: github.event_name != 'pull_request'
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-node@v1
#        with:
#          node-version: '12.x'
#      - uses: webfactory/ssh-agent@v0.5.0
#        with:
#          ssh-private-key: ${{ secrets.GH_DAPP_DEPLOY }}
#
#      - name: Deploy 🚀
#        uses: JamesIves/github-pages-deploy-action@4.1.4
#        with:
#          branch: gh-pages # The branch the action should deploy to.
#          folder: build # The folder the action should deploy.
#          ssh-key: true